apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    postgres.kubedb.com/version: "9.5"
  creationTimestamp: 2017-06-09T05:28:05Z
  generation: 1
  labels:
    kubedb.com/kind: Postgres
  name: postgres-db-pg
  namespace: default
  resourceVersion: "20135407"
  selfLink: /apis/apps/v1beta1/namespaces/default/statefulsets/postgres-db-pg
  uid: 6a4dcd51-4cd4-11e7-8b69-12f236046fba
spec:
  replicas: 1
  selector:
    matchLabels:
      kubedb.com/kind: Postgres
      kubedb.com/name: postgres-db
  serviceName: kubedb
  template:
    metadata:
      annotations:
        postgres.kubedb.com/version: "9.5"
      creationTimestamp: null
      labels:
        kubedb.com/kind: Postgres
        kubedb.com/name: postgres-db
    spec:
      containers:
      - args:
        - basic
        image: kubedb/postgres:9.5-db
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /srv/postgres/secrets
          name: secret
        - mountPath: /var/pv
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret
        secret:
          defaultMode: 420
          secretName: postgres-db-admin-auth
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: gp2
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    status:
      phase: Pending
status:
  replicas: 1
