apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: gp2
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: 2017-06-09T05:50:33Z
  labels:
    kubedb.com/kind: Elasticsearch
    kubedb.com/name: elasticsearch-db
  name: data-elasticsearch-db-es-0
  namespace: default
  resourceVersion: "20138435"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/data-elasticsearch-db-es-0
  uid: 8da23e7c-4cd7-11e7-8b69-12f236046fba
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-8da23e7c-4cd7-11e7-8b69-12f236046fba
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
