apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.beta.kubernetes.io/storage-class: gp2
  creationTimestamp: 2017-06-09T05:50:34Z
  labels:
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
  name: pvc-8da23e7c-4cd7-11e7-8b69-12f236046fba
  resourceVersion: "20138433"
  selfLink: /api/v1/persistentvolumespvc-8da23e7c-4cd7-11e7-8b69-12f236046fba
  uid: 8e0ddb45-4cd7-11e7-8b69-12f236046fba
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1b/vol-0d699d1413482ac4d
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-elasticsearch-db-es-0
    namespace: default
    resourceVersion: "20138427"
    uid: 8da23e7c-4cd7-11e7-8b69-12f236046fba
  persistentVolumeReclaimPolicy: Delete
status:
  phase: Bound
