apiVersion: v1
kind: Service
metadata:
  labels:
    kubedb.com/kind: Elasticsearch
    kubedb.com/name: e1
  name: e1
  namespace: demo
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    kubedb.com/kind: Elasticsearch
    kubedb.com/name: e1
    node.role.client: set
