# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.kubedb.appscode.com
  labels:
    app: kubedb
webhooks:
- name: admission.kubedb.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.kubedb.appscode.com/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - kubedb.appscode.com
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail
