# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.kubedb.com
  labels:
    app: kubedb
webhooks:
- name: admission.kubedb.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.kubedb.com/v1alpha1/reviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    - DELETE
    apiGroups:
    - kubedb.com
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail
