{{ if .Values.catalog.postgres }}
---
apiVersion: kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "9.6"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6"

---
apiVersion: kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "9.6.7"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6.7"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6.7"

---
apiVersion: kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "10.2"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:10.2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:10.2"
{{ end }}
