{{ if .Values.catalog.redis }}
---
apiVersion: kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4.0.6"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"
{{ end }}
