apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-db
spec:
  version: 9.5
  backupSchedule:
    cronExpression: "@every 6h"
    storageSecretName: "secret-for-bucket"
    gcs:
      bucket: "bucket-for-snapshot"
