apiVersion: v1
description: 'KubeDB by AppsCode - Backup your Kubernetes Volumes'
name: kubedb
version: 0.2.0
appVersion: 0.6.3
home: https://github.com/kubedb/cli
icon: https://cdn.appscode.com/images/icon/kubedb.png
sources:
  - https://github.com/kubedb/cli
maintainers:
  - name: appscode
    email: support@appscode.com
