---
apiVersion: kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.4"
  labels:
    app: kubedb
spec:
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.4"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.4"

---
apiVersion: kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.6"
  labels:
    app: kubedb
spec:
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.6"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.6"
