---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "9.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:9.6"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:9.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6-v1"
  labels:
    app: kubedb
spec:
  version: "9.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:9.6-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres_exporter:v0.4.6"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:9.6-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "9.6.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:9.6.7"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:9.6.7"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7-v1"
  labels:
    app: kubedb
spec:
  version: "9.6.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:9.6.7-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres_exporter:v0.4.6"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:9.6.7-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "10.2"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:10.2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2-v1"
  labels:
    app: kubedb
spec:
  version: "10.2"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:10.2-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres_exporter:v0.4.6"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:10.2-v2"

---
# After 0.9.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.6"
  labels:
    app: kubedb
spec:
  version: "10.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:10.6"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres_exporter:v0.4.7"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:10.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "11.1"
  labels:
    app: kubedb
spec:
  version: "11.1"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres:11.1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres_exporter:v0.4.7"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/postgres-tools:11.1"
