---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4-v1"
  labels:
    app: kubedb
spec:
  version: "4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4.0"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0-v1"
  labels:
    app: kubedb
spec:
  version: "4.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4.0-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4.0.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4.0.6-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6-v1"
  labels:
    app: kubedb
spec:
  version: "4.0.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis:4.0.6-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/redis_exporter:v0.21.1"

