apiVersion: kubedb.com/v1alpha1
kind: Elastic
metadata:
  name: e3
  namespace: demo
spec:
  version: 2.3.1
  replicas: 1
  doNotPause: true
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
