apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: recovered
  namespace: demo
spec:
  version: 2.3.1
  storage:
    class: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
      name: e1-xyz
