apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "kubedb-${KUBEDB_OPERATOR_NAME}-servicemonitor"
  namespace: ${PROMETHEUS_NAMESPACE}
  labels:
    ${SERVICE_MONITOR_LABEL_KEY}: ${SERVICE_MONITOR_LABEL_VALUE}
spec:
  namespaceSelector:
    matchNames:
    - ${KUBEDB_NAMESPACE}
  selector:
    matchLabels:
       app: kubedb
  endpoints:
  - port: api
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/kubedb-${KUBEDB_OPERATOR_NAME}-apiserver-cert/tls.crt
      serverName: "kubedb-${KUBEDB_OPERATOR_NAME}.${KUBEDB_NAMESPACE}.svc"
