apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-09T05:50:33Z
  labels:
    kubedb.com/name: elasticsearch-db
  name: elasticsearch-db
  namespace: default
  resourceVersion: "20138422"
  selfLink: /api/v1/namespaces/default/services/elasticsearch-db
  uid: 8d942813-4cd7-11e7-8b69-12f236046fba
spec:
  clusterIP: 10.0.174.251
  ports:
  - name: api
    port: 9200
    protocol: TCP
    targetPort: api
  - name: tcp
    port: 9300
    protocol: TCP
    targetPort: tcp
  selector:
    kubedb.com/name: elasticsearch-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
