apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: gp2
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: 2017-06-09T05:28:05Z
  labels:
    kubedb.com/kind: Postgres
    kubedb.com/name: postgres-db
  name: data-postgres-db-pg-0
  namespace: default
  resourceVersion: "20135412"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/data-postgres-db-pg-0
  uid: 6a5126c2-4cd4-11e7-8b69-12f236046fba
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-6a5126c2-4cd4-11e7-8b69-12f236046fba
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
