apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.beta.kubernetes.io/storage-class: gp2
  creationTimestamp: 2017-06-09T05:28:06Z
  labels:
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
  name: pvc-6a5126c2-4cd4-11e7-8b69-12f236046fba
  resourceVersion: "20135410"
  selfLink: /api/v1/persistentvolumespvc-6a5126c2-4cd4-11e7-8b69-12f236046fba
  uid: 6aac5836-4cd4-11e7-8b69-12f236046fba
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1b/vol-0c247692419f3f967
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-postgres-db-pg-0
    namespace: default
    resourceVersion: "20135404"
    uid: 6a5126c2-4cd4-11e7-8b69-12f236046fba
  persistentVolumeReclaimPolicy: Delete
status:
  phase: Bound
