apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-09T05:28:05Z
  labels:
    kubedb.com/name: postgres-db
  name: postgres-db
  namespace: default
  resourceVersion: "20135398"
  selfLink: /api/v1/namespaces/default/services/postgres-db
  uid: 6a3915d9-4cd4-11e7-8b69-12f236046fba
spec:
  clusterIP: 10.0.40.174
  ports:
  - name: port
    port: 5432
    protocol: TCP
    targetPort: port
  selector:
    kubedb.com/name: postgres-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
