apiVersion: kubedb.com/v1beta1
kind: Elastic
metadata:
  name: elasticsearch-db
spec:
  version: 2.3.1
  replicas: 1
  backupSchedule:
    cronExpression: "@every 6h"
    bucketName: "bucket-for-snapshot"
    storageSecret:
      secretName: "secret-for-bucket"
