apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-xyz
  labels:
    kubedb.com/kind: Elastic
spec:
  databaseName: elasticsearch-db
  bucketName: "bucket-for-snapshot"
  storageSecret:
    secretName: "secret-for-bucket"
