apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "kubedb.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.enable }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: "{{ template "kubedb.name" . }}"
    release: "{{ .Release.Name }}"
