apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mongodb-db
  labels:
    app: kubedb
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mongodb-snapshot
  labels:
    app: kubedb
spec: #same spec as db
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
